### ISSUE TITLE
Link to appveyor.yml is broken

### ISSUE THREAD

**Issue by marciofrayze** [elm-explorations/test#150]
At "Running tests on CI" topic, this link is broken:

https://github.com/rtfeldman/elm-css/blob/master/appveyor.yml

**Comment by harrysarson** [comment]
See https://github.com/rtfeldman/elm-css/commit/aa6e23178f74b640aae7fc297749b5c1477d501c#diff-180360612c6b8c4ed830919bbb4dd459

**Comment by Anton-4** [comment]
Ok if I submit a PR to fix this in the README? I think it would also be valuable to add a link for github actions ci, like here in [dillonkearns/elm-cli-options-parser](https://github.com/dillonkearns/elm-cli-options-parser/blob/master/.github/workflows/ci.yml).

**Comment by harrysarson** [comment]
This [dillonkearns/elm-cli-options-parser](https://github.com/dillonkearns/elm-cli-options-parser/blob/master/.github/workflows/ci.yml) config file is huge! I would love to see a much simpler config we can link to (unless that really is the minimum configuration you need to run elm-test test using github actions).

**Comment by Anton-4** [comment]
True, I will make and test a minimal version.

**Comment by Anton-4** [comment]
This is a minimal config:
```yml
name: Elm Actions

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm clean-install
      - name: elm-test
        run: npx --no-install elm-test
```

Should I save it as a gist, update the readme and submit a PR?
